In [2]:
import pandas as pd

url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-11.parquet"
columns = ['PULocationID', 'DOLocationID', 'trip_distance', 'total_amount', 'tpep_pickup_datetime']
df = pd.read_parquet(url, columns=columns).head(1000)
df.head()

,PULocationID,DOLocationID,trip_distance,total_amount,tpep_pickup_datetime
0,43,186,1.68,22.15,2025-11-01 00:13:25
1,142,237,2.28,24.94,2025-11-01 00:49:07
2,163,238,2.70,25.62,2025-11-01 00:07:19
3,138,261,12.87,86.14,2025-11-01 00:00:00
4,138,37,8.40,48.65,2025-11-01 00:18:50

In [3]:
df

,PULocationID,DOLocationID,trip_distance,total_amount,tpep_pickup_datetime
0,43,186,1.68,22.15,2025-11-01 00:13:25
1,142,237,2.28,24.94,2025-11-01 00:49:07
2,163,238,2.70,25.62,2025-11-01 00:07:19
3,138,261,12.87,86.14,2025-11-01 00:00:00
4,138,37,8.40,48.65,2025-11-01 00:18:50
...,...,...,...,...,...
995,246,186,0.70,13.95,2025-11-01 00:42:06
996,100,164,0.15,9.45,2025-11-01 00:48:58
997,234,113,0.43,18.06,2025-11-01 00:53:59
998,239,116,3.30,28.35,2025-11-01 00:12:11
999,107,79,0.90,18.90,2025-11-01 00:51:36

In [6]:
row = df.iloc[0]
row

PULocationID                             43
DOLocationID                            186
trip_distance                          1.68
total_amount                          22.15
tpep_pickup_datetime    2025-11-01 00:13:25
Name: 0, dtype: object

In [11]:
q = int(row.tpep_pickup_datetime.timestamp()*1000)
q

1761956005000

In [4]:
from dataclasses import dataclass

@dataclass
class Ride:
    PULocationID: int
    DOLocationID: int
    trip_distance: float
    total_amount: float
    tpep_pickup_datetime: int

In [6]:
ride = Ride(
    PULocationID=1,
    DOLocationID=2,
    trip_distance=10.5,
    total_amount=25.0,
    tpep_pickup_datetime=1761956005000
)

In [5]:
import json
from kafka import KafkaProducer

def json_serializer(data):
    return json.dumps(data).encode('utf-8')

server = 'localhost:9092'

producer = KafkaProducer(
    bootstrap_servers=[server],
    value_serializer=json_serializer
)

In [8]:
import dataclasses
ride_dict = dataclasses.asdict(ride)
json.dumps(ride_dict).encode('utf-8')

b'{"PULocationID": 1, "DOLocationID": 2, "trip_distance": 10.5, "total_amount": 25.0, "tpep_pickup_datetime": 1761956005000}'

In [ ]:
topic_name = 'rides'

producer.send(topic_name, value=ride_dict)
producer.flush()